=== Pedja1201/wbis_pedja22/Gradivo za I Kolokvijum/PripremaKolokvijumAutomobili/SkladisteAutomobilaXSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.singidunum.ac.rs/skladiste"
    xmlns:skl="http://www.singidunum.ac.rs/skladiste">

    <xs:element name="automobili">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="skl:automobil" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="skladiste">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="vlasnik" type="skl:TLice"/>
                <xs:element name="adresa">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="broj" type="xs:int"/>
                            <xs:element name="ulica" type="xs:string"/>
                            <xs:element name="grad" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element ref="skl:automobili"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="automobil">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="skl:proizvodjac"/>
                <xs:element name="vlasnik" type="skl:TLice"/>
                <xs:element name="tockove">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="dijametar" type="xs:decimal"/>
                            <xs:element name="gume" type="xs:string"/>
                            <xs:element ref="skl:proizvodjac"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element ref="skl:motor"/>
            </xs:sequence>
            <xs:attribute name="sifraSasije">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value=""/>
                        <xs:enumeration value=""/>
                        <xs:pattern value="d{5}-{3}-{4}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="godinaProizvodnje" type="xs:int"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="proizvodjac">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="naziv" type="xs:string"/>
                <xs:element name="drzavaPorekla" type="xs:string"/>
                <xs:element name="zastupnik" type="skl:TLice"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="motor">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="snaga" type="xs:integer"/>
                <xs:element name="obrtniMomenat" type="xs:integer"/>
                <xs:element ref="skl:proizvodjac"/>
                <xs:choice>
                    <xs:element name="datumServisiranja" form="qualified" nillable="false">
                        <xs:simpleType>
                            <xs:restriction base="xs:date">
                                <xs:whiteSpace value="collapse"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                </xs:choice>
            </xs:sequence>
            <xs:attribute form="unqualified" name="tipGoriva" use="optional">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="benzin"/>
                        <xs:enumeration value="dizel"/>
                        <xs:enumeration value="hibridni"/>
                        <xs:enumeration value="elektricna energija"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:complexType abstract="true" name="TLice"/>
    <xs:complexType name="TFizickoLice">
        <xs:complexContent>
            <xs:extension base="skl:TLice">
                <xs:sequence>
                    <xs:element name="ime" type="xs:string"/>
                    <xs:element name="prezime" type="xs:string"/>
                    <xs:element name="jmbg">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:pattern value="d{13}"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TPravnoLice">
        <xs:complexContent>
            <xs:extension base="skl:TLice">
                <xs:sequence>
                    <xs:element name="naziv" type="xs:string"/>
                    <xs:element name="maticniBroj">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:pattern value="d{13}"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
</xs:schema>

=== Pedja1201/wbis_pedja22/Gradivo za I Kolokvijum/PripremaKolokvijumAutomobili/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<automobil xmlns="http://www.singidunum.ac.rs/skladiste"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.singidunum.ac.rs/skladiste file:/D:/Singidunum%20III/Letnji%20semestar%202021_22/Veb%20bazirani%20info%20sistemi/PripremaKolokvijumAutomobili/SkladisteAutomobilaXSD.xsd" sifraSasije="ddddd-------" godinaProizvodnje="0">
    <proizvodjac>
        <naziv>naziv0</naziv>
        <drzavaPorekla>drzavaPorekla0</drzavaPorekla>
        <zastupnik xmlns:skl="http://www.singidunum.ac.rs/skladiste" xsi:type="skl:TFizickoLice">
            <ime>ime0</ime>
            <prezime>prezime0</prezime>
            <jmbg>ddddddddddddd</jmbg>
        </zastupnik>
    </proizvodjac>
    <vlasnik xmlns:skl="http://www.singidunum.ac.rs/skladiste" xsi:type="skl:TFizickoLice">
        <ime>ime1</ime>
        <prezime>prezime1</prezime>
        <jmbg>ddddddddddddd</jmbg>
    </vlasnik>
    <tockove>
        <dijametar>0</dijametar>
        <gume>gume0</gume>
        <proizvodjac>
            <naziv>naziv1</naziv>
            <drzavaPorekla>drzavaPorekla1</drzavaPorekla>
            <zastupnik xmlns:skl="http://www.singidunum.ac.rs/skladiste" xsi:type="skl:TFizickoLice">
                <ime>ime2</ime>
                <prezime>prezime2</prezime>
                <jmbg>ddddddddddddd</jmbg>
            </zastupnik>
        </proizvodjac>
    </tockove>
    <motor tipGoriva="benzin">
        <snaga>0</snaga>
        <obrtniMomenat>0</obrtniMomenat>
        <proizvodjac>
            <naziv>naziv2</naziv>
            <drzavaPorekla>drzavaPorekla2</drzavaPorekla>
            <zastupnik xmlns:skl="http://www.singidunum.ac.rs/skladiste" xsi:type="skl:TFizickoLice">
                <ime>ime3</ime>
                <prezime>prezime3</prezime>
                <jmbg>ddddddddddddd</jmbg>
            </zastupnik>
        </proizvodjac>
        <datumServisiranja>2006-05-04</datumServisiranja>
    </motor>
</automobil>
