=== Pedja1201/wbis_pedja22/vezbe2/LicnaKarta/LicnaKarta.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT licnaKarta (podaci_o_osobi, podaci_o_karti) >
<!ELEMENT podaci_o_osobi (licniPodaci+) > <!-- Kao primer koji nam sluzi za dodavanje atributa 
(podacima O Osobi smo uveli ponavljanje putem '+' i tu istu koristimo dalje u dobavljanju podataka) -->
<!ELEMENT licniPodaci (ime, prezime,datumRodjenja, pol, slika, potpis) >
<!ATTLIST licniPodaci 
JMBG CDATA #REQUIRED >

<!ELEMENT ime (#PCDATA) >
<!ELEMENT prezime (#PCDATA) >
<!ELEMENT datumRodjenja (#PCDATA) >
<!ELEMENT pol (#PCDATA) >
<!ELEMENT slika (#PCDATA) >
<!ELEMENT potpis (#PCDATA) >

<!ELEMENT podaci_o_karti (brojLicneKarte, datumIzdavanja, datumIsteka, dokumentIzdaje) >
<!ELEMENT brojLicneKarte (#PCDATA) >
<!ELEMENT datumIzdavanja (#PCDATA) >
<!ELEMENT datumIsteka (#PCDATA) >
<!ELEMENT dokumentIzdaje (#PCDATA) >

=== Pedja1201/wbis_pedja22/vezbe2/LicnaKarta/LicnaKarta.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE licnaKarta SYSTEM "LicnaKarta.dtd">
<!-- XML dokument koji je izgenerisan iz LicnaKarta.dtd (napravljen xml dokument na osnovu dtd dokumenta) -->
<licnaKarta>
    <podaci_o_osobi>
        <licniPodaci JMBG="12000987">
            <ime>Milica</ime>
            <prezime>Maric</prezime>
            <datumRodjenja>02.02.2000</datumRodjenja>
            <pol>Zenski</pol>
            <slika></slika>
            <potpis></potpis>
        </licniPodaci>
    </podaci_o_osobi>
    <podaci_o_karti>
        <brojLicneKarte>999222</brojLicneKarte>
        <datumIzdavanja>12.09.2022</datumIzdavanja>
        <datumIsteka>12.09.2023</datumIsteka>
        <dokumentIzdaje>PU Beograd</dokumentIzdaje>
    </podaci_o_karti>
</licnaKarta>
