=== Pedja1201/wbis_pedja22/vezbe2/RacunarDomaci.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT racunar ((monitor, kuciste, periferije+) | (kuciste, periferije+, monitor)) >

<!ELEMENT monitor (model+, frekvencijaOsvezivanja, proizvodjac+, rezolucija+) >
<!ELEMENT model (#PCDATA) >
<!ELEMENT frekvencijaOsvezivanja (#PCDATA) >
<!ELEMENT proizvodjac (#PCDATA) >
<!ELEMENT rezolucija (#PCDATA) >
<!ATTLIST rezolucija 
visina CDATA #REQUIRED 
sirina CDATA #REQUIRED>

<!ELEMENT kuciste (model, proizvodjac, komponente) >
<!ATTLIST komponente 
tip (maticnaPloca|memorija|procesor|grafickaKartica) #REQUIRED >
<!ELEMENT komponente (#PCDATA) >

<!ELEMENT periferije (mis, tastatura) >
<!ELEMENT mis (model, DPI, proizvodjac) >
<!ELEMENT DPI (#PCDATA) >
<!ELEMENT tastatura (model, proizvodjac) >
<!ATTLIST tastatura 
tipTastera (membranski|mehanicki) #REQUIRED >

=== Pedja1201/wbis_pedja22/vezbe2/RacunarDomaci.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE racunar SYSTEM "RacunarDomaci.dtd">
<racunar>
    <monitor>
        <model></model>
        <frekvencijaOsvezivanja></frekvencijaOsvezivanja>
        <proizvodjac></proizvodjac>
        <rezolucija visina="2" sirina="2"></rezolucija>
    </monitor>
    
    <kuciste>
        <model></model>
        <proizvodjac></proizvodjac>
        <komponente tip="maticnaPloca"></komponente>
    </kuciste>
    <periferije>
        <mis>
            <model></model>
            <DPI></DPI>
            <proizvodjac></proizvodjac>
        </mis>
        <tastatura tipTastera="membranski">
            <model></model>
            <proizvodjac></proizvodjac>
        </tastatura>
    </periferije>
</racunar>
