=== Pedja1201/wbis_pedja22/vezbe2/skladisteVezbaKlkl.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT skladista ((vlasnik, vozila, adresa) | (adresa, vozila, vlasnik) | (vozila, vlasnik, adresa)) >

<!ELEMENT adresa (broj?, ulica, grad) >
<!ELEMENT broj (#PCDATA) >
<!ELEMENT ulica (#PCDATA) >
<!ELEMENT grad (#PCDATA) >

<!ELEMENT vozila (proizvodjac, motor, tockovi, vlasnikAuta) >
<!ATTLIST vozila
sifraSasije CDATA #REQUIRED
godinaProizvodnje CDATA #REQUIRED>
<!ELEMENT proizvodjac (#PCDATA) >
<!ELEMENT motor (snaga, obrtniMomenat, proizvodjacMotora, datumServisiranja) >
<!ATTLIST motor
tipGoriva (beznin | dizel | hibridni | elektricnaEnergija) #REQUIRED>
<!ELEMENT snaga (#PCDATA) >
<!ELEMENT obrtniMomenat (#PCDATA) >
<!ELEMENT proizvodjacMotora (#PCDATA) >
<!ELEMENT datumServisiranja (#PCDATA) >
<!ELEMENT tockovi (dijametar, proizvodjacTockova) >
<!ATTLIST tockovi
gume (zimske | letnje ) #REQUIRED>
<!ELEMENT dijametar (#PCDATA) >
<!ELEMENT proizvodjacTockova (#PCDATA) >
<!ELEMENT vlasnikAuta (#PCDATA) >

<!ELEMENT vlasnik (ime, prezime, jmbg ) >
<!ELEMENT ime (#PCDATA) >
<!ELEMENT prezime (#PCDATA) >
<!ELEMENT jmbg (#PCDATA) >

=== Pedja1201/wbis_pedja22/vezbe2/skladisteVezbaKlk.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE skladista SYSTEM "skladisteVezbaKlkl.dtd">
<skladista>
    <adresa>
        <ulica>Prvomajska 4</ulica>
        <grad>Pavlis</grad>
    </adresa>
    <vozila sifraSasije="121212222R" godinaProizvodnje="2008">
        <proizvodjac>Skoda DOO Sabac</proizvodjac>
        <motor tipGoriva="dizel">
            <snaga>1400 kubika</snaga>
            <obrtniMomenat>1,3</obrtniMomenat>
            <proizvodjacMotora>Fiat</proizvodjacMotora>
            <datumServisiranja>2021</datumServisiranja>
        </motor>
        <tockovi gume="letnje">
            <dijametar>12</dijametar>
            <proizvodjacTockova>Mishelin</proizvodjacTockova>
        </tockovi>
        <vlasnikAuta>Marko Peric</vlasnikAuta>
    </vozila>
    <vlasnik>
        <ime>Nikola</ime>
        <prezime>Nikolic</prezime>
        <jmbg>1293322211</jmbg>
    </vlasnik>
</skladista>
