=== Pedja1201/wbis_pedja22/PredragRadak_I_Kolokvijum/FakultetXSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.singidunum.ac.rs" xmlns:fax="http://www.singidunum.ac.rs">
    <xs:element name="fakulteti">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="fax:fakultet"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="fakultet">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="naziv" type="xs:string"/>
                <xs:element name="adresa" type="xs:string"/>
                <xs:element ref="fax:nastavnici"/>
                <xs:element ref="fax:predmeti"/>
            </xs:sequence>
            <xs:attribute name="datumOsnivanja" type="xs:date"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="nastavnici">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" minOccurs="0" name="nastavnik"
                    type="fax:TNastavnik"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType abstract="true" name="TNastavnik">
        <xs:sequence>
            <xs:element name="ime" type="xs:string"/>
            <xs:element name="prezime" type="xs:string"/>
            <xs:element name="plata">
                <xs:simpleType>
                    <xs:restriction base="xs:double">
                        <xs:maxExclusive value="2"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="katedra">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="informatika"/>
                    <xs:enumeration value="ekonomija"/>
                    <xs:enumeration value="turizam"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
    <xs:complexType name="TAsistent">
        <xs:complexContent>
            <xs:extension base="fax:TNastavnik">
                <xs:choice>
                    <xs:element name="doktroskeStudije" type="xs:boolean"/>
                </xs:choice>
                <xs:attribute name="zvanje">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="bachelor"/>
                            <xs:enumeration value="master"/>
                            <xs:enumeration value="doktor"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TProfesor">
        <xs:complexContent>
            <xs:extension base="fax:TNastavnik">
                <xs:sequence>
                    <xs:element ref="fax:radovi"/>
                </xs:sequence>
                <xs:attribute name="datumDoktoriranja" type="xs:date"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:element name="radovi">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" name="objavljeniRad">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="naslov" type="xs:string"/>
                            <xs:element maxOccurs="unbounded" minOccurs="0" name="kljucneReci"
                                type="xs:string"/>
                            <xs:element maxOccurs="1" name="datumObjavljivanja" type="xs:date"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="predmeti">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="fax:predmet"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="predmet">
        <xs:complexType>
            <xs:all>
                <xs:element name="naziv" type="xs:string"/>
                <xs:element name="brojCasova" type="xs:integer"/>
                <xs:element ref="fax:angazovaniNastavnici"/>
            </xs:all>
            <xs:attribute name="sifraPredmeta" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="angazovaniNastavnici">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="fax:nastavnici"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Pedja1201/wbis_pedja22/PredragRadak_I_Kolokvijum/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<fakulteti xmlns="http://www.singidunum.ac.rs"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.singidunum.ac.rs file:/D:/Singidunum%20III/Letnji%20semestar%202021_22/Veb%20bazirani%20info%20sistemi/PredragRadak_I_Kolokvijum/FakultetXSD.xsd">
    <fakultet datumOsnivanja="2006-05-04">
        <naziv>naziv0</naziv>
        <adresa>adresa0</adresa>
        <nastavnici>
            <nastavnik xmlns:fax="http://www.singidunum.ac.rs" xsi:type="fax:TProfesor" datumDoktoriranja="2006-05-04" katedra="informatika">
                <ime>ime0</ime>
                <prezime>prezime0</prezime>
                <plata>-49.5</plata>
                <radovi>
                    <objavljeniRad>
                        <naslov>naslov0</naslov>
                        <datumObjavljivanja>2006-05-04</datumObjavljivanja>
                    </objavljeniRad>
                    <objavljeniRad>
                        <naslov>naslov1</naslov>
                        <datumObjavljivanja>2006-05-04</datumObjavljivanja>
                    </objavljeniRad>
                </radovi>
            </nastavnik>
            <nastavnik xmlns:fax="http://www.singidunum.ac.rs" xsi:type="fax:TProfesor" datumDoktoriranja="2006-05-04" katedra="informatika">
                <ime>ime1</ime>
                <prezime>prezime1</prezime>
                <plata>-49.5</plata>
                <radovi>
                    <objavljeniRad>
                        <naslov>naslov2</naslov>
                        <datumObjavljivanja>2006-05-04</datumObjavljivanja>
                    </objavljeniRad>
                    <objavljeniRad>
                        <naslov>naslov3</naslov>
                        <datumObjavljivanja>2006-05-04</datumObjavljivanja>
                    </objavljeniRad>
                </radovi>
            </nastavnik>
        </nastavnici>
        <predmeti>
            <predmet sifraPredmeta="sifraPredmeta1">
                <naziv>naziv1</naziv>
                <brojCasova>0</brojCasova>
                <angazovaniNastavnici>
                    <nastavnici>
                    </nastavnici>
                    <nastavnici>
                    </nastavnici>
                </angazovaniNastavnici>
            </predmet>
            <predmet sifraPredmeta="sifraPredmeta3">
                <naziv>naziv2</naziv>
                <brojCasova>0</brojCasova>
                <angazovaniNastavnici>
                    <nastavnici>
                    </nastavnici>
                    <nastavnici>
                    </nastavnici>
                </angazovaniNastavnici>
            </predmet>
        </predmeti>
    </fakultet>
    <fakultet datumOsnivanja="2006-05-04">
        <naziv>naziv3</naziv>
        <adresa>adresa1</adresa>
        <nastavnici>
            <nastavnik xmlns:fax="http://www.singidunum.ac.rs" xsi:type="fax:TProfesor" datumDoktoriranja="2006-05-04" katedra="informatika">
                <ime>ime2</ime>
                <prezime>prezime2</prezime>
                <plata>-49.5</plata>
                <radovi>
                    <objavljeniRad>
                        <naslov>naslov4</naslov>
                        <datumObjavljivanja>2006-05-04</datumObjavljivanja>
                    </objavljeniRad>
                    <objavljeniRad>
                        <naslov>naslov5</naslov>
                        <datumObjavljivanja>2006-05-04</datumObjavljivanja>
                    </objavljeniRad>
                </radovi>
            </nastavnik>
            <nastavnik xmlns:fax="http://www.singidunum.ac.rs" xsi:type="fax:TProfesor" datumDoktoriranja="2006-05-04" katedra="informatika">
                <ime>ime3</ime>
                <prezime>prezime3</prezime>
                <plata>-49.5</plata>
                <radovi>
                    <objavljeniRad>
                        <naslov>naslov6</naslov>
                        <datumObjavljivanja>2006-05-04</datumObjavljivanja>
                    </objavljeniRad>
                    <objavljeniRad>
                        <naslov>naslov7</naslov>
                        <datumObjavljivanja>2006-05-04</datumObjavljivanja>
                    </objavljeniRad>
                </radovi>
            </nastavnik>
        </nastavnici>
        <predmeti>
            <predmet sifraPredmeta="sifraPredmeta5">
                <naziv>naziv4</naziv>
                <brojCasova>0</brojCasova>
                <angazovaniNastavnici>
                    <nastavnici>
                    </nastavnici>
                    <nastavnici>
                    </nastavnici>
                </angazovaniNastavnici>
            </predmet>
            <predmet sifraPredmeta="sifraPredmeta7">
                <naziv>naziv5</naziv>
                <brojCasova>0</brojCasova>
                <angazovaniNastavnici>
                    <nastavnici>
                    </nastavnici>
                    <nastavnici>
                    </nastavnici>
                </angazovaniNastavnici>
            </predmet>
        </predmeti>
    </fakultet>
</fakulteti>
