=== Pedja1201/wbis_pedja22/vezbe2/Knjizara/knjizara.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT knjizara (vlasnik, knjige?) > <!-- ? znaci da je knjiga opciona(Moze i ne mora da se oznaci) -->
<!ELEMENT vlasnik (ime, prezime) >
<!ELEMENT ime (#PCDATA) >
<!ELEMENT prezime (#PCDATA) >

<!ELEMENT knjige (knjiga+) > <!-- + ponavlja se vise puta -->
<!ELEMENT knjiga (naslov, ISBN, autor) >
<!ATTLIST knjiga 
language (en|de|es) #REQUIRED  
pages CDATA #IMPLIED
><!-- Postavljanje tributa -->

<!ATTLIST naslov 
jezik (en|fra|ita|ger|esp ) #REQUIRED  ><!-- Postavljanje tributa -->
<!ELEMENT ISBN (#PCDATA) >
<!ELEMENT autor ((imeAutora, prezimeAutora, datumRodjenja, datumSmrti?) | pen_name) > <!-- | znaci ili (nije bitan redosled ko ce prvi) ? znaci opciono nije obavezno-->
<!ELEMENT imeAutora (#PCDATA) >
<!ELEMENT prezimeAutora (#PCDATA) >
<!ELEMENT datumRodjenja (#PCDATA) >
<!ELEMENT datumSmrti (#PCDATA) >

=== Pedja1201/wbis_pedja22/vezbe2/Knjizara/knjizara.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE knjizara SYSTEM "knjizara.dtd">
<knjizara>
    <vlasnik>
        <ime>Marko</ime>
        <prezime>Markovic</prezime>
    </vlasnik>
    <knjige>
        <knjiga language="en">
            <naslov>Na drini Cuprija</naslov>
            <ISBN>OO99</ISBN>
            <autor>  <!-- Pravi stablo za sto autor u DTD ima ime i prezime ILI pen_name -->
                <ime>Ivo</ime>
                <prezime>Andric</prezime>
            </autor>
        </knjiga>
    </knjige>
</knjizara>
