=== Pedja1201/wbis_pedja22/vezbe2/Uplatnica/Uplata.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT uplata (tekstualniTip , numerickiTip, dodatni_podaci_o_uplati) >
<!ELEMENT tekstualniTip (uplatilac, svrhaUplate, primalac) >
<!ELEMENT uplatilac (ime, prezime, adresa, potpis)>
<!ELEMENT ime (#PCDATA)>
<!ELEMENT prezime (#PCDATA)>

<!ELEMENT adresa (adrese+) >
<!ELEMENT adrese (grad, ulica) >
<!ELEMENT grad (#PCDATA)>
<!ELEMENT ulica (#PCDATA)>
<!ATTLIST adrese  
postanski_broj CDATA #REQUIRED>   <!-- Dodat primer za atribute u adresi za broj i postBroj -->
<!ELEMENT potpis (#PCDATA)>

<!ELEMENT svrhaUplate (#PCDATA)>
<!ELEMENT primalac (#PCDATA)>

<!ELEMENT numerickiTip (sifraPlacanja, valuta, iznos, racunPrimaoca, model?, pozivNaBroj) >
<!ELEMENT sifraPlacanja (#PCDATA) >
<!ELEMENT valuta (#PCDATA) >
<!ELEMENT iznos (#PCDATA) >
<!ELEMENT racunPrimaoca (#PCDATA) >
<!ELEMENT model (#PCDATA) >
<!ELEMENT pozivNaBroj (#PCDATA) >

<!ELEMENT dodatni_podaci_o_uplati (mestoUplate, datumUplate) >
<!ELEMENT mestoUplate (#PCDATA) >
<!ELEMENT datumUplate (#PCDATA) >

=== Pedja1201/wbis_pedja22/vezbe2/Uplatnica/UplataXML.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE uplata SYSTEM "Uplata.dtd">
<uplata>
    <tekstualniTip>
        <uplatilac>
            <ime>Predrag</ime>
            <prezime>Radak</prezime>
            <adresa>
                <adrese postanski_broj="26300">
                    <grad>Vrsac</grad>
                    <ulica>Radakova 5</ulica>
                </adrese>
            </adresa>
            <potpis></potpis>
        </uplatilac>
        <svrhaUplate>Druga rata clanarine</svrhaUplate>
        <primalac>Marko marinkovic, Beograd</primalac>
    </tekstualniTip>
    
    <numerickiTip>
        <sifraPlacanja>987</sifraPlacanja>
        <valuta>RSD</valuta>
        <iznos>15000</iznos>
        <racunPrimaoca>2092882-282892</racunPrimaoca>
        <pozivNaBroj>12092</pozivNaBroj>
    </numerickiTip>
    
    <dodatni_podaci_o_uplati>
        <mestoUplate>Vrsac</mestoUplate>
        <datumUplate>29.08.2022</datumUplate>
    </dodatni_podaci_o_uplati>
    
</uplata>
